service:
  name: serverless-tg-bot
app: serverless-tg-bot
org: villeheikkila

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}
    OPENWEATHER_TOKEN: ${env:OPENWEATHER_TOKEN}

functions:
  webhook:
    handler: handler.webhook
    timeout: 30
    events:
      - http: POST /webhook
